- name: Remove any existing Go installation
  ansible.builtin.file:
    path: "{{ go_root }}"
    state: absent

- name: Download Go binary
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.{{ go_arch }}.tar.gz"
    dest: "/tmp/go{{ go_version }}.{{ go_arch }}.tar.gz"

- name: Extract Go tarball
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.{{ go_arch }}.tar.gz"
    dest: /usr/local
    remote_src: yes
    extra_opts: ["--strip-components=1"]

- name: Set Go environment variables
  ansible.builtin.lineinfile:
    path: /etc/profile.d/go.sh
    line: 'export PATH=$PATH:/usr/local/go/bin'
    create: yes
